name: Build browser extensions
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [chrome, firefox]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
      - run: npm run lint
      - run: npm run build ${{ matrix.target }}

      - run: cd dist && zip -r ../dist.zip .
      - uses: actions/upload-artifact@v1
        with:
          name: dist-zip-${{ matrix.target }}
          path: ./dist.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: dist-zip-chrome
      - uses: actions/download-artifact@v1  # duplicate step as there's currently no way to specify a matrix for a single step
        with:
          name: dist-zip-firefox
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: false
          draft: true
          body: |
            #### Added
            -

            #### Changed
            -

            #### Fixed
            -

            ---
            Chrome extension: ${{ secrets.EXT_URL_CHROME }}
            Firefox extension: ${{ secrets.EXT_URL_FIREFOX }}
          # urls are secrets to allow changing them without having to modify the workflow file
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: wolframalpha-moresteps-chrome.zip
          asset_path: ./dist-zip-chrome/dist.zip
          asset_content_type: application/zip
          upload_url: ${{ steps.create-release.outputs.upload_url }}
      - uses: actions/upload-release-asset@v1  # duplicate step as there's currently no way to specify a matrix for a single step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: wolframalpha-moresteps-firefox.zip
          asset_path: ./dist-zip-firefox/dist.zip
          asset_content_type: application/zip
          upload_url: ${{ steps.create-release.outputs.upload_url }}
